
See alsoThrowing and Catching Exceptions.

Thetry-catchblocks are used to catch any exceptions or other throwable objects within the code.
Here's whattry-catchblocks looks like:

try {statement1.1statement1.2...statement1.n} catch (exception1) {statement2.1...statement2.n}

Thecode listing 3.6tries to print all the arguments that have been passed to the program. However, if there not enough arguments, it will throw an exception.


In addition to the try and catch blocks, afinallyblock may be present. The finally block is always executed, even if an exception is thrown. It may appear with or without a catch block, but always with a try block.
Here is what a finally block looks like:

try {statement1.1statement1.2...statement1.n} catch (exception1) {statement2.1...statement2.n} finally {statement3.1...statement3.n}

